### ISSUE TITLE
NPM build fails on OS X

### ISSUE THREAD

**Issue by danielcuthbert** [rnd-ash/OpenVehicleDiag#1]
> cargo build --release && napi build --release

    Updating crates.io index
    Updating git repository `https://github.com/napi-rs/napi-rs`
  Downloaded num-traits v0.2.14
  Downloaded num-bigint v0.2.6
  Downloaded autocfg v1.0.1
  Downloaded serde_derive v1.0.117
  Downloaded num-rational v0.2.4
  Downloaded lazy_static v1.4.0
  Downloaded libc v0.2.80
  Downloaded bitflags v1.2.1
  Downloaded serde_json v1.0.59
  Downloaded libloading v0.6.5
  Downloaded num v0.2.1
  Downloaded itoa v0.4.6
  Downloaded num-iter v0.1.42
  Downloaded unicode-xid v0.2.1
  Downloaded num-complex v0.2.4
  Downloaded cfg-if v1.0.0
  Downloaded num-integer v0.1.44
  Downloaded quote v1.0.7
  Downloaded ryu v1.0.5
  Downloaded syn v1.0.48
  Downloaded num-derive v0.3.3
  Downloaded proc-macro2 v1.0.24
  Downloaded serde v1.0.117
  Downloaded 23 crates (1.4 MB) in 1.34s
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.48
   Compiling serde_derive v1.0.117
   Compiling ryu v1.0.5
   Compiling serde v1.0.117
   Compiling serde_json v1.0.59
   Compiling bitflags v1.2.1
   Compiling itoa v0.4.6
   Compiling cfg-if v1.0.0
   Compiling libc v0.2.80
   Compiling napi-sys v0.4.7 (https://github.com/napi-rs/napi-rs#68017ce2)
   Compiling lazy_static v1.4.0
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling num-bigint v0.2.6
   Compiling num-rational v0.2.4
   Compiling num-iter v0.1.42
   Compiling num-complex v0.2.4
   Compiling napi-build v0.2.1 (https://github.com/napi-rs/napi-rs#68017ce2)
   Compiling libloading v0.6.5
   Compiling ovd v0.1.0 (/Users/daniel/Documents/Car Pwnage/OpenVehicleDiag/app)
   Compiling quote v1.0.7
   Compiling num v0.2.1
   Compiling num-derive v0.3.3
   Compiling napi-derive v0.5.1 (https://github.com/napi-rs/napi-rs#68017ce2)
   Compiling J2534Common v0.1.0 (/Users/daniel/Documents/Car Pwnage/OpenVehicleDiag/MacchinaM2-J2534-Rust/J2534Common)
   Compiling napi v0.5.1 (https://github.com/napi-rs/napi-rs#68017ce2)
warning: crate `J2534Common` should have a snake case name
  |
  = note: `#[warn(non_snake_case)]` on by default
  = help: convert the identifier to snake case: `j2534_common`

warning: 1 warning emitted

warning: unused imports: `Error`, `JsFunction`, `JsString`, `JsUndefined`, `Status`
 --> src/lib.rs:6:33
  |
6 | use napi::{CallContext, Result, JsString, Status, Error, JsUnknown, JsFunction, JsUndefined, Module, JsNumber};
  |                                 ^^^^^^^^  ^^^^^^  ^^^^^             ^^^^^^^^^^  ^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `serde_json`
 --> src/lib.rs:8:5
  |
8 | use serde_json;
  |     ^^^^^^^^^^

warning: unused import: `TryInto`
  --> src/lib.rs:11:20
   |
11 | use std::convert::{TryInto, TryFrom};
   |                    ^^^^^^^

warning: unused import: `Symbol`
 --> src/passthru.rs:4:27
  |
4 | use libloading::{Library, Symbol};
  |                           ^^^^^^

warning: unused import: `J2534Common::PassthruError::ERR_FAILED`
  --> src/passthru.rs:22:5
   |
22 | use J2534Common::PassthruError::ERR_FAILED;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0369]: binary operation `==` cannot be applied to type `J2534Common::FilterType`
   --> src/passthru.rs:308:24
    |
308 |         if filter_type == FLOW_CONTROL_FILTER && flow_control == None {
    |            ----------- ^^ ------------------- J2534Common::FilterType
    |            |
    |            J2534Common::FilterType

error[E0369]: binary operation `==` cannot be applied to type `std::option::Option<&J2534Common::PASSTHRU_MSG>`
   --> src/passthru.rs:308:63
    |
308 |         if filter_type == FLOW_CONTROL_FILTER && flow_control == None {
    |                                                  ------------ ^^ ---- std::option::Option<_>
    |                                                  |
    |                                                  std::option::Option<&J2534Common::PASSTHRU_MSG>

error[E0308]: mismatched types
   --> src/passthru.rs:313:13
    |
312 |         let p_msg = match pattern {
    |                           ------- this expression has type `&J2534Common::PASSTHRU_MSG`
313 |             None => std::ptr::null() as *const PASSTHRU_MSG,
    |             ^^^^ expected struct `J2534Common::PASSTHRU_MSG`, found enum `std::option::Option`
    |
    = note: expected struct `J2534Common::PASSTHRU_MSG`
                 found enum `std::option::Option<_>`

error[E0308]: mismatched types
   --> src/passthru.rs:314:13
    |
312 |         let p_msg = match pattern {
    |                           ------- this expression has type `&J2534Common::PASSTHRU_MSG`
313 |             None => std::ptr::null() as *const PASSTHRU_MSG,
314 |             Some(m) => m as *const PASSTHRU_MSG
    |             ^^^^^^^ expected struct `J2534Common::PASSTHRU_MSG`, found enum `std::option::Option`
    |
    = note: expected struct `J2534Common::PASSTHRU_MSG`
                 found enum `std::option::Option<_>`

error[E0308]: mismatched types
   --> src/passthru.rs:330:46
    |
330 |             _ => Err(PassthruError::from_raw(res).unwrap())
    |                                              ^^^ expected `u32`, found `i32`
    |
help: you can convert an `i32` to `u32` and panic if the converted value wouldn't fit
    |
330 |             _ => Err(PassthruError::from_raw(res.try_into().unwrap()).unwrap())
    |                                              ^^^^^^^^^^^^^^^^^^^^^^^

error[E0615]: attempted to take value of method `stop_msg_filter` on type `&passthru::PassthruDrv`
   --> src/passthru.rs:336:35
    |
336 |         let res = unsafe { (&self.stop_msg_filter)(channel_id, filter_id) };
    |                                   ^^^^^^^^^^^^^^^ method, not a field
    |
help: use parentheses to call the method
    |
336 |         let res = unsafe { (&self.stop_msg_filter(_, _))(channel_id, filter_id) };
    |                                                  ^^^^^^

error[E0615]: attempted to take value of method `set_programming_voltage` on type `&passthru::PassthruDrv`
   --> src/passthru.rs:345:35
    |
345 |         let res = unsafe { (&self.set_programming_voltage)(dev_id, pin, voltage) };
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^ method, not a field
    |
help: use parentheses to call the method
    |
345 |         let res = unsafe { (&self.set_programming_voltage(_, _, _))(dev_id, pin, voltage) };
    |                                                          ^^^^^^^^^

error: aborting due to 7 previous errors; 5 warnings emitted

Some errors have detailed explanations: E0308, E0369, E0615.
For more information about an error, try `rustc --explain E0308`.

**Comment by rnd-ash** [comment]
Closing issue, JS app is no longer active, use app_rust
