### ISSUE TITLE
OS X /usr/share issues

### ISSUE THREAD

**Issue by danielcuthbert** [rnd-ash/OpenVehicleDiag#2]
OS X makes use of System Integrity Protection (SIP) to protect the filesystem from malicious things happening on it, so using /usr/share won't be ideal as the user has to disable SIP. 

Possible fix for the Macchina driver in comms.rs is 

```
#[cfg(OSX)]
fn get_comm_port() -> Option<String> {
    if let Ok(content) = std::fs::read_to_string(" ~/Library/Macchina/passthru/macchina.json") {
        return match serde_json::from_str::<serde_json::Value>(content.as_str()) {
            Ok(v) => v["COM-PORT"].as_str().map(String::from),
            Err(_) => None
        }
    }
    None
}
```

Then all we'd need to do is fix the build.sh file to look at what OS is being run and adapt accordingly

**Comment by rnd-ash** [comment]
Does the directory
```
~/.passthru/
```
Work for OSX? I want to avoid making the build process for Linux and OSX different

**Comment by danielcuthbert** [comment]
Yeah and this might make it easier to support both OS X and Leeeeeeeenux users.
