### ISSUE TITLE
Coding

### ISSUE THREAD

**Issue by logglogg** [rnd-ash/OpenVehicleDiag#41]
Is it possible to send data to the ecu? 
I‘m talking about coding. I would like to enable/disable features e.g. coming home function for lights.

**Comment by rnd-ash** [comment]
This is technically possible (If you know what payloads to send to ECUs). However adding this feature for specific ECUs would be a legal gray area.....so coding is NOT planned for this program.

**Comment by logglogg** [comment]
okay, thanks.
but what I don’t understand why this is a gray zone? 
If we us for example labels from xentry or vag, is it not the same?
