### ISSUE TITLE
[QUESTION] Protocol

### ISSUE THREAD

**Issue by shtry** [rnd-ash/OpenVehicleDiag#8]
Hello,

I have a question.

Does the "OpenVehicleDiag" tool support "UDS(Unified Diagnostic Services)" protocol?

Or, are J2534-2 protocol and UDS(Unified Diagnostic Services) the same protocol?

Thank you!

**Comment by rnd-ash** [comment]
J2534-2 and D-PDU are HARDWARE protocols - These allow for an application to talk to an OBD-II adapter

UDS and KWP2000 are Diagnostic protocols which allow for an application to request diagnostic information from an ECU. UDS and KWP2000 are implemented in the application (WIP) using the J2534-2 API to talk to the ECU.

**Comment by shtry** [comment]
@rnd-ash  Thanks for the good answer!
